# This is a basic workflow to help you get started with Actions

name: gif comment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  issues:
    type: [ open ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  comment:
    if: github.event_name == 'issues'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: add funny gif comment
        uses: actions/checkout@v2
        id: GifComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'gif'
